name: "🐞 BUG report"
description: "Report an unexpected behavior in PlotIN"
title: "[BUG] Short summary"
labels: ["bug"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve PlotIN!  
        Please keep the report as short and clear as possible.

  - type: input
    id: summary
    attributes:
      label: Short summary
      placeholder: "Y-axis loses negative values after switching back to linear scale"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: "What do you click / change, step by step?"
      placeholder: |
        1. Open PlotIN
        2. Paste data into the main text area
        3. Select Line plot
        4. Change Y-scale to log
        5. Change Y-scale back to linear
    validations:
      required: true

  - type: textarea
    id: behavior
    attributes:
      label: Expected vs. actual behavior
      description: "What did you expect to happen, and what happens instead?"
      placeholder: |
        Expected: Y-axis shows full range from -10 to +10.
        Actual: Only positive values (0 to 10) are visible.
    validations:
      required: true

  - type: textarea
    id: data_sample
    attributes:
      label: Data sample (pasted)
      description: "Paste a small example of the data you used in PlotIN. PlotIN currently works only with pasted data."
      placeholder: |
        X,Y
        -10,-5
        -5,-2
        0,0
        5,2
        10,5
    validations:
      required: false

  - type: input
    id: version
    attributes:
      label: PlotIN version
      placeholder: "e.g. PlotIN 1.0 (Windows)"
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating system
      placeholder: "e.g. Windows 11 x64, macOS Sequoia"
    validations:
      required: true
