name: "✨ Enhancement request"
description: "Suggest a new feature or improvement for PlotIN"
title: "[Enhancement] Short summary"
labels: ["Enhancement"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Have an idea that could make PlotIN better?  
        Keep it short and focused on your real use case.

  - type: input
    id: summary
    attributes:
      label: Short summary
      placeholder: "Add EMF export without using Inkscape"
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Why is this useful?
      description: "How would this help you in your real workflow?"
      placeholder: |
        Example:
        I regularly need high-quality scientific plots for reports and papers.
        Having this feature directly inside PlotIN saves time and avoids external tools.
    validations:
      required: true

  - type: textarea
    id: idea
    attributes:
      label: Suggested approach (optional)
      description: "If you already have a specific idea for how this could work, describe it here."
      placeholder: |
        Example:
        Add an option in the Save Figure dialog to enable/disable EMF export.
        If Inkscape is installed, PlotIN can automatically convert the SVG to EMF behind the scenes.
        If not installed, the EMF option simply remains unavailable.
    validations:
      required: false

