name: "💬 Support request"
description: "Ask a question about using PlotIN"
title: "[Support] Short summary"
labels: ["support"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Use this template if you need help using PlotIN or if something is unclear.

  - type: input
    id: summary
    attributes:
      label: Question summary
      placeholder: "How can I center both axes at the origin?"
    validations:
      required: true

  - type: textarea
    id: question
    attributes:
      label: Full question
      description: "Explain what you are trying to do."
      placeholder: |
        I want both X and Y axes to cross at (0, 0) in the middle of the plot.
        I tried changing the axis limits, but I am not sure which option controls this.
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context (optional)
      description: "What were you doing in PlotIN when this question appeared?"
      placeholder: "e.g. I pasted data, selected a bar plot, opened the Axes & Ticks dialog..."
    validations:
      required: false

  - type: input
    id: version
    attributes:
      label: PlotIN version (optional)
      placeholder: "e.g. PlotIN 1.0 (Windows)"
    validations:
      required: false

  - type: input
    id: os
    attributes:
      label: Operating system (optional)
      placeholder: "e.g. Windows 10, macOS Sequoia..."
    validations:
      required: false
